services:
  - type: web
    name: pgAdmin
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PGADMIN_DEFAULT_EMAIL
        value: admin@example.com
      - key: PGADMIN_DEFAULT_PASSWORD
        value: admin
    healthCheckPath: /
